### ISSUE TITLE
Link para o canal do youtube quebrado

### ISSUE THREAD

**Issue by lucasfv1** [ti-lcsf/links-interessantes-flutter#1]
Olá, o link **Por que usar o Flutter do Canal Polimorfismo** está quebrado, você poderia corrigir?

![erro-url](https://user-images.githubusercontent.com/51465884/134188541-2da37603-d1dd-4303-bfef-2acd1217b3ff.png)

**Comment by ti-lcsf** [comment]
Problema resolvido com o commit: a39be04279121403315cace850e58dd56af4b303

Obrigado por avisar!
